[package]
name = "fum"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
mpris = "2.0.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
ratatui-image = { version = "4.1.0", features = ["crossterm"] }
reqwest = { version = "0.12.9", features = ["blocking"] }
